# Generated by Django 3.2.2 on 2021-05-09 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_owner', models.CharField(max_length=30)),
                ('image_title', models.CharField(max_length=50)),
                ('image_slug', models.SlugField(max_length=200)),
                ('image_permissions', models.CharField(choices=[('+', 'PUBLIC'), ('-', 'PRIVATE')], default='+', max_length=1)),
                ('image_src', models.FileField(upload_to='images/')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
            ],
        ),
    ]
