# Generated by Django 3.2.2 on 2021-05-10 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imgrepo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image_title',
        ),
        migrations.AlterField(
            model_name='image',
            name='image_src',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
