# Generated by Django 3.2.2 on 2021-05-10 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imgrepo', '0002_auto_20210509_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_src',
            field=models.ImageField(upload_to='static/media/images/'),
        ),
    ]
